services:
  learnassist.api:
    image: ${DOCKER_REGISTERY-}learnassistapi
    container_name: LearnAssist.Api
    build:
      context: .
      dockerfile: src/API/LearnAssist.Api/Dockerfile
    environment:
      - TZ=Asia/Tehran
    ports:
      - 5000:8080
      - 5001:8081
        
  learnassist.database:
    image:  postgres:latest
    container_name: Learnassist.Database
    environment:
      - POSTGRES_DB=learnassist_modular
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kayhan14@
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

